version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs-app
    container_name: nodejs-app
    restart: unless-stopped
    depends_on:
     - db
    ports:
      - "8080:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:3306 -- /home/node/app/node_modules/.bin/nodemon app.js 

  db:
    image: mydb-app
    container_name: db
    restart: unless-stopped
    environment:
      - DATABASE_HOST=db
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_PASSWORD= 123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  node_modules: